env:
  dev
spring:
  application:
    name: uFly-zuul
server:
  port: 9085

ribbon:
  eureka:
    enabled: true
zuul:
  #  prefix: /api
  routes:
#    traditional-url:                             #传统的路由配置,此名称可以自定义
#      path: /client/**                           #映射的url
#      url: http://localhost:9083/           #被映射的url
    user-manage:                       #用户中心
      path: /api-u/**
      sensitiveHeaders:
      service-id: uFly-user-server           #服务名
    oauth:                       #认证中心
      path: /api-o/**
      sensitiveHeaders:
      service-id: uFly-oauth-server          #服务名
  add-proxy-headers: true
